version: '3.8'

services:
  web:
    image: eriksf/biocontainers-tacc-web:latest
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
